clear all; clc; %#ok<CLALL>
DATA = load('data.mat');

DATA.WTPfpU(DATA.WTPfpU == 401) = Inf;
DATA.WTPhpU(DATA.WTPhpU == 401) = Inf;

INPUT.bounds = [DATA.WTPfpL DATA.WTPfpU];


Distributions = {...
    0  'Normal'; ...
    1  'Logistic'; ...
    2  'Extreme_Value'; ...
    3  'Generalized_Extreme_Value'; ...
    4  'tLocationScale'; ...
    5  'Uniform'; ...
    6  'Johnson_SU'; ...

    10  'Expotential'; ...
    11  'Lognormal'; ...
    12  'Loglogistic'; ...
    13  'Weibull'; ...
    14  'Rayleigh'; ...
    15  'Gamma'; ...
    16  'BirnbaumSaunders'; ...
    17  'Generalized_Pareto'; ...
    18  'Inverse_Gaussian'; ...
    19  'Nakagami'; ...
    20  'Rician'; ...
%     21  'Johnson_SB'; ...

    31  'Poisson'; ...
    32  'Negative_Binomial'};

for i = 1:size(Distributions,1);
%     if i == 6 || i == 9; continue; end
    WTP.(Distributions{i,2}) = DistFit(INPUT,Distributions{i,1});
end

for i = 1:size(Distributions,1);
    LL(i,1:2) = {Distributions{i,2}, WTP.(Distributions{i,2}).fval}; %#ok<SAGROW>
end


